// Check full report content for match 19432248
const mongoose = require('mongoose');
require('dotenv').config();

const Report = require('./models/Report');

async function checkFullReport() {
  try {
    await mongoose.connect(process.env.DBURI);
    console.log('Connected to MongoDB');
    
    const matchId = 19432248;
    
    // Get Southampton report
    const report = await Report.findOne({ 
      match_id: matchId, 
      team_slug: 'southampton' 
    }).lean();
    
    if (!report) {
      console.log('❌ Report not found');
      return;
    }
    
    console.log('\n=== FULL REPORT STRUCTURE ===\n');
    console.log('Headline:', report.headline);
    console.log('\n--- SUMMARY PARAGRAPHS (main content) ---');
    report.summary_paragraphs?.forEach((p, i) => {
      console.log(`\nParagraph ${i + 1}:`);
      console.log(p);
    });
    
    console.log('\n--- KEY MOMENTS ---');
    report.key_moments?.forEach((m, i) => {
      console.log(`${i + 1}. ${m}`);
    });
    
    console.log('\n--- COMMENTARY (additional analysis) ---');
    report.commentary?.forEach((c, i) => {
      console.log(`\nCommentary ${i + 1}:`);
      console.log(c);
    });
    
    console.log('\n--- PLAYER OF THE MATCH ---');
    console.log(`Player: ${report.player_of_the_match?.player}`);
    console.log(`Reason: ${report.player_of_the_match?.reason}`);
    
    console.log('\n--- EMBEDDED TWEETS ---');
    console.log(`Count: ${report.embedded_tweets?.length || 0}`);
    report.embedded_tweets?.forEach((t, i) => {
      console.log(`\n${i + 1}. @${t.author.userName}:`);
      console.log(`   ${t.text}`);
    });
    
    console.log('\n--- SOURCES ---');
    report.sources?.forEach((s, i) => {
      console.log(`${i + 1}. ${s}`);
    });
    
    console.log('\n--- METADATA ---');
    console.log(`Generated by: ${report.meta?.generated_by}`);
    console.log(`Pipeline version: ${report.meta?.pipeline?.version}`);
    console.log(`Total paragraphs: ${report.summary_paragraphs?.length || 0}`);
    console.log(`Total word count (summary): ${report.summary_paragraphs?.join(' ').split(' ').length || 0}`);
    
  } catch (error) {
    console.error('Error:', error);
  } finally {
    await mongoose.disconnect();
  }
}

checkFullReport();
