// Check reports for match 19432248
const mongoose = require('mongoose');
require('dotenv').config();

const Report = require('./models/Report');
const Match = require('./models/Match');

async function checkReports() {
  try {
    await mongoose.connect(process.env.DBURI);
    console.log('Connected to MongoDB');
    
    const matchId = 19432248;
    
    // Get match details
    const match = await Match.findOne({ match_id: matchId }).lean();
    if (!match) {
      console.log(`❌ Match ${matchId} not found`);
      return;
    }
    
    console.log('\n=== MATCH DETAILS ===');
    console.log(`Match ID: ${match.match_id}`);
    console.log(`Home: ${match.home_team} (slug: ${match.home_team_slug})`);
    console.log(`Away: ${match.away_team} (slug: ${match.away_team_slug})`);
    console.log(`Date: ${match.date}`);
    console.log(`Status: ${match.match_status?.state}`);
    console.log(`Reports in match doc:`, match.reports);
    
    // Get all reports for this match
    const reports = await Report.find({ match_id: matchId }).lean();
    
    console.log('\n=== REPORTS ===');
    console.log(`Total reports: ${reports.length}`);
    
    for (const report of reports) {
      console.log(`\n--- Report for ${report.team_name} (${report.team_slug}) ---`);
      console.log(`Report ID: ${report._id}`);
      console.log(`Created: ${report.created_at}`);
      console.log(`Updated: ${report.updated_at}`);
      console.log(`Headline: ${report.headline}`);
      
      // Check embedded tweets
      console.log(`\nEmbedded Tweets: ${report.embedded_tweets?.length || 0}`);
      if (report.embedded_tweets && report.embedded_tweets.length > 0) {
        console.log('Tweet IDs:');
        report.embedded_tweets.forEach((t, i) => {
          console.log(`  ${i + 1}. ${t.tweet_id} - @${t.author?.userName}: ${t.text?.substring(0, 80)}...`);
        });
      } else {
        console.log('  ⚠️ No embedded tweets found!');
      }
      
      // Check sources
      console.log(`\nSources: ${report.sources?.length || 0}`);
      if (report.sources && report.sources.length > 0) {
        report.sources.forEach((s, i) => {
          console.log(`  ${i + 1}. ${s}`);
        });
      }
      
      // Check meta
      console.log(`\nMeta:`);
      console.log(`  Generated by: ${report.meta?.generated_by}`);
      console.log(`  Model: ${report.meta?.model}`);
      console.log(`  Pipeline version: ${report.meta?.pipeline?.version}`);
      console.log(`  Total time: ${report.meta?.pipeline?.total_time_ms}ms`);
    }
    
  } catch (error) {
    console.error('Error:', error);
  } finally {
    await mongoose.disconnect();
  }
}

checkReports();
