// models/Report.js
const mongoose = require('mongoose');

const SourceSchema = new mongoose.Schema({
  events: { type: Boolean, default: false },
  player_stats: { type: Boolean, default: false },
  tweets: { type: [String], default: [] } // store identifiers or authors used
}, { _id: false });

// We intentionally store the original SportMonks player_ratings payload
// inside the Report so we don't synthesize or alter provider data.
// Use a flexible mixed schema to permit the provider's shape verbatim.
const PlayerRatingSchema = new mongoose.Schema({}, { _id: false, strict: false });

const ReportSchema = new mongoose.Schema({
  match_id: { type: Number, required: true, index: true },
  team_id: { type: Number, required: true },
  team_focus: { type: String }, // e.g. "West Ham United" (which side this report targets)
  // normalized slug for the team (preferred key for uniqueness)
  team_slug: { type: String, lowercase: true, trim: true, index: true },
  team_perspective: { type: String }, // team this report is written from perspective of
  headline: { type: String },
  status: { type: String, default: 'draft' }, // draft | finalizing | final
  last_synced_at: { type: Date, default: null },
  finalized_at: { type: Date, default: null },
  
  // Generated content from AI model (structured)
  generated: {
    headline: { type: String },
    summary_paragraphs: { type: [String], default: [] },
    key_moments: { type: [String], default: [] },
    commentary: { type: [String], default: [] },
    player_of_the_match: {
      player: { type: String },
      reason: { type: String }
    },
    sources: { type: [String], default: [] }
  },
  
  // Legacy/consolidated content field
  content: { type: String },
  source_counts: { type: Object, default: {} },
  summary_paragraphs: { type: [String], default: [] },
  key_moments: { type: [String], default: [] },
  // keep raw comments from the match provider so generated reports can quote or summarise them
  comments: { type: [mongoose.Schema.Types.Mixed], default: [] },
  // Commentary generated by the model (short editorial lines)
  commentary: { type: [String], default: [] },
  
  // Player ratings from the match (provider data)
  player_ratings: { type: [PlayerRatingSchema], default: [] },
  
  // Normalized lineup data with ratings integrated
  lineup: {
    home: [{
      player_id: { type: mongoose.Schema.Types.Mixed },
      player_name: { type: String },
      jersey_number: { type: Number },
      position_id: { type: Number },
      rating: { type: Number, default: null }
    }],
    away: [{
      player_id: { type: mongoose.Schema.Types.Mixed },
      player_name: { type: String },
      jersey_number: { type: Number },
      position_id: { type: Number },
      rating: { type: Number, default: null }
    }]
  },
  
  // Player of the Match (prefer this term over "man of the match")
  potm: {
    player: { type: String, default: null },
    rating: { type: Number, default: null },
    reason: { type: String, default: null },
    sources: { type: SourceSchema, default: () => ({}) }
  },
  // raw_evidence snapshot (optional): keep small to avoid huge docs
  evidence_ref: {
    events_count: Number,
    tweets_count: Number
  },
  meta: {
    generated_by: String, // e.g. 'openai:gpt-4o-mini'
    prompt_hash: String
  }
}, { timestamps: true });

// Ensure only one report per match + team slug. Use sparse so older docs without a slug
// won't fail index creation; migration should populate `team_slug` for existing docs.
ReportSchema.index({ match_id: 1, team_slug: 1 }, { unique: true, sparse: true });

module.exports = mongoose.model('Report', ReportSchema);
